version: '0.1'

services:
  database:
    image: postgres
    container_name: microsservices-first-study
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ms_client
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local